from os import name
from django.urls import path
from .views import (CreateChannel,
                    copy_journey_data,
                    copy_skill_journey_data,
                    ChannelList, CreateJourneyContentPageSetup, DeletePageSetup, EditPageSetup, JourneyContentPageSetup, JourneyContentList, ShowJourneyConfigPage,
                    UpdateChannel,
                    UpdateSubChannel,
                    SubChannel,
                    CourseContent,
                    CreateContent, journey_list, load_program_team,
                    upload_video,
                    upload_subtitle,
                    update_data,
                    update_subtitle,
                    translate_subtitles,
                    UserContent,
                    ChannelContent,
                    EditChannel,
                    EditContentData,
                    DeleteContentData,
                    AddField,
                    UpdateOrder,
                    ReadContent,
                    PendingContent,
                    UpdateChannelStatus,
                    ChannelGroupView,
                    CreateChannelGroup,
                    SelectChannelGroup,
                    BrowseChannel,
                    JoinRequest,
                    ApproveRequest,
                    RejectContent,
                    JoinChannel,
                    ApproveContent,
                    UpdateContentTitle,
                    UpdateOption,
                    CopyContent,
                    CourseList,
                    DeleteCourse,
                    DeleteChannel,
                    EditChannelGroup,
                    DeleteChannelGroup,
                    ChannelUserList,
                    AllAdminContent,
                    DeleteOption,
                    DeleteSubtitleOption,
                    CorrectAnswer,
                    ContentQuizAsnwer,
                    ContentPollAnswer,
                    UploadContentBanner,
                    CheckSubChannel,
                    ConfigCourse,
                    ConfigCourseList,
                    SubChannelList,
                    AdminReadContent,
                    DeleteConfigRecord,
                    ConfigCourseEdit,
                    UserJourney,
                    JourneyReport,
                    JourneyAllReport,
                    CompleteSkill,
                    CourseSummary,
                    ReviceMode,
                    ThankYou,
                    MentoringJourneyList,
                    SelfPacedJourneyList,
                    SetupJourneyContent,
                    UpdatesetupJournetData,
                    DeleteJourneyContent,
                    ChannelContent_V2,
                    add_link_type_content,
                    program_announce_wp_report,
                    UpdateContentOrder,
                    UpdateContentChecked,
                    FilterSetupJourneyContent,
                    check_journey_exist,
                    PublicAnnouncement,
                    journey_all_content,
                    update_public_announcement,
                    PublicAnnouncementList,
                    EditPublicAnnouncement,
                    ShowJourneyConfigSignupPage,
                    upload_activity_file,
                    UserActivityDetail,
                    AllActivity,
                    AddCertificate, CertificateList,
                    UpdateCertificate,
                    )

app_name = "content"
urlpatterns = [
    path('journey-create/', CreateChannel.as_view(), name="create-channel"),
    path('copy-journey/', copy_journey_data, name="copy_journey_data"),
    path('copy-skill-journey/', copy_skill_journey_data, name="copy_skill_journey_data"),
    path('program-team-list/', load_program_team, name="program_team_list"),
    path('sub-journey-create/', SubChannel.as_view(), name="create-sub-channel"),
    path('journey-list/', ChannelList.as_view(), name="channel_list"),
    path('sub-journey-list/', SubChannelList.as_view(), name="sub_channel_list"),
    path('journeys/', BrowseChannel.as_view(), name="browse_channel"),
    path('journeys/<str:pk>/', BrowseChannel.as_view(), name="browse_channel_with_id"),
    path('edit/<uuid:pk>/', UpdateChannel.as_view(), name="edit-channel"),
    path('edit-sub-channel/<uuid:pk>/', UpdateSubChannel.as_view(), name="edit_sub_channel"),
    path('delete/', DeleteCourse.as_view(), name="delete_course"),
    path('delete-option', DeleteOption.as_view(), name="delete_cd_option"),
    path('delete-subtitle-option', DeleteSubtitleOption.as_view(), name="delete_subtitle_option"),
    path('journey/delete/', DeleteChannel.as_view(), name="delete_channel"),
    path('proficiency-level/delete/', DeleteChannelGroup.as_view(), name="delete_channel_group"),
    path('course-content/', CourseContent.as_view(), name="course_content"),
    path('create-content/', CreateContent.as_view(), name="create_content"),
    path('upload-videos/', upload_video, name="upload-videos"),
    path('upload-subtitle/', upload_subtitle, name="upload-subtitle"),
    path('update-subtitle/', update_subtitle, name="update-subtitle"),
    path('translate-subtitle/', translate_subtitles, name="translate-subtitle"),
    path('update-data/', update_data, name="update-data"),
    path('upload-activity-file', upload_activity_file, name="upload_activity_file"),
    path('my-content/', UserContent.as_view(), name="user-content"),
    path('all-content/', AllAdminContent.as_view(), name="all-content"),
    path('journey/<uuid:Channel>', ChannelContent_V2.as_view(), name="Channel_content"),
    path('journey/v2/<uuid:Channel>', ChannelContent_V2.as_view(), name="Channel_content_v2"),
    path('content/edit/<uuid:pk>/', EditContentData.as_view(), name="edit_content"),
    path('update_channel/', EditChannel.as_view(), name="update_channel"),
    path('update_status/', UpdateChannelStatus.as_view(), name="update_status"),
    path('add-field/', AddField.as_view(), name="add-field"),
    path('update-Option/', UpdateOption.as_view(), name="update_option"),
    path('update-order/', UpdateOrder.as_view(), name='update-order'),
    path('update-content-order/', UpdateContentOrder.as_view(), name='update-content-order'),
    path('update-content-checked/', UpdateContentChecked.as_view(), name='update-content-checked'),
    path('<uuid:pk>', AdminReadContent.as_view(), name="admin_read_content"),
    path('<uuid:pk>/channel/<uuid:group>', ReadContent.as_view(), name="read_content"),
    path('user/', PendingContent.as_view(), name="pending_content"),
    path('proficiency-level/', ChannelGroupView.as_view(), name="channel_group"),
    path('proficiency-level/create/', CreateChannelGroup.as_view(), name="create_channel_group"),
    path('proficiency-level/edit/<uuid:pk>', EditChannelGroup.as_view(), name="edit_channel_group"),
    path('delete-content-data/content/<uuid:content>/<int:pk>', DeleteContentData.as_view(),
         name="delete_content_data"),
    path('delete-journey-content/', DeleteJourneyContent.as_view(), name="delete-journey-content"),
    path('add_link_type_content/', add_link_type_content.as_view(), name="add_link_type_content"),
    path('join-request/', JoinRequest.as_view(), name="join_request"),
    path('join-journey/', JoinChannel.as_view(), name="join_channel"),
    path('approve-request/<int:pk>', ApproveRequest.as_view(), name="approve_request"),
    path('reject-content/<int:pk>', RejectContent.as_view(), name="reject_content"),
    path('approve-content/<int:pk>/', ApproveContent.as_view(), name="approve_content"),
    path('update-content-title/', UpdateContentTitle.as_view(), name="update_content_title"),
    path('copy-content/', CopyContent.as_view(), name="copy_content"),
    path('proficiency-level/<uuid:channel_id>/', ChannelGroupView.as_view(), name="channel_groups_list"),
    path('course-list/<uuid:channel_group>', CourseList.as_view(), name="view_course_list"),
    path('journey-content-list/<uuid:channel_id>', JourneyContentList.as_view(), name="journey_content_list"),
    path('journey-user/<uuid:channel_id>/', ChannelUserList.as_view(), name="user_list"),
    path('correct_answer', CorrectAnswer.as_view(), name="correct_answer"),
    path("quiz-answer", ContentQuizAsnwer.as_view(), name="quiz_answer"),
    path('poll-answer', ContentPollAnswer.as_view(), name="poll_answer"),
    path('upload_banner', UploadContentBanner.as_view(), name="upload_banner"),
    path('check_sub_channel', CheckSubChannel.as_view(), name="check_sub_channel"),
    # @@@@@@@@@@@@@@@@@@@@@ for Api  @@@@@@@@@@@@@@@@@@@@
    path('config', ConfigCourse.as_view(), name="config_course"),
    # path('config/edit/', EditConfigCourse.as_view(), name="edit_config_course"),
    path('config-list', ConfigCourseList.as_view(), name="config_course_list"),
    path('edit-config-list/<uuid:pk>', ConfigCourseEdit.as_view(), name="config_course_edit"),
    path('delete_skill_config', DeleteConfigRecord.as_view(), name="delete_skill_config"),
    path('select_channel_group', SelectChannelGroup.as_view(), name="select_channel_group"),
    path('user-journey/<uuid:pk>', UserJourney.as_view(), name="user_journey"),
    path('complete_skill/<uuid:content>/<uuid:group>', CompleteSkill.as_view(), name="complete_skill"),
    path('thank-you/<uuid:content>/<uuid:group>', ThankYou.as_view(), name="thank_you"),
    path('journey-report/<uuid:pk>', JourneyReport.as_view(), name="journey_report"),
    path('journey-all-user/<uuid:channel>', JourneyAllReport.as_view(), name="journey_all_report"),
    path('summary/<uuid:pk>/channel/<uuid:group>', CourseSummary.as_view(), name="course_summary"), 
    path('revise/<uuid:pk>/<uuid:group>', ReviceMode.as_view(), name="revice_mode"),
    path('mentoring_journey/', MentoringJourneyList.as_view(), name="mentoring_journey"),
    path('self_paced_journey/', SelfPacedJourneyList.as_view(), name="self_paced_journey"),
    path("setup-journey-content/<uuid:journey_id>", SetupJourneyContent.as_view(), name="setup-journey-content"),
    path("update-setup-journey-content/", UpdatesetupJournetData.as_view(), name="update-setup-journey-content"),
    path("whatsapp-message-report", program_announce_wp_report.as_view(), name="program_announce_wp_report"),
    path('create-journey-page-setup/', CreateJourneyContentPageSetup.as_view(), name="create_journey_page_setup"),
    path('list-journey-page-setup/', JourneyContentPageSetup.as_view(), name="list_journey_page_setup"),
    path('delete-setup/', DeletePageSetup.as_view(), name="delete_setup"),
    path('edit-setup/<uuid:pk>/', EditPageSetup.as_view(), name="edit_setup"),
    path('journey-list', journey_list, name="journey_list"),
    path("filter-setup-journey-content", FilterSetupJourneyContent.as_view(), name="filter_setup_journey_content"),
    path('journey-page/<uuid:pk>/', ShowJourneyConfigPage.as_view(), name="journey_page"),
    path('journey-signup-page/<uuid:pk>/', ShowJourneyConfigSignupPage.as_view(), name="journey_signup_page"),
    path('check-journey-exist/', check_journey_exist, name="check_journey_exist"),
    path('public-announcement/', PublicAnnouncement.as_view(), name="public_announcement"),
    path('journey-all-content/', journey_all_content, name="journey_all_content"),
    path('public-announcement-list/', PublicAnnouncementList.as_view(), name="public_announcement_list"),
    path('edit-public-announcement/<uuid:pk>', EditPublicAnnouncement.as_view(), name="edit_public_announcement"),
    path('update-public-announcement/<uuid:pk>', update_public_announcement, name="update_public_announcement"),
    path('user-activity-detail/<int:activity_id>/<str:user_type>', UserActivityDetail.as_view(), name='user_activity_detail'),
    path('all-activity', AllActivity.as_view(), name="all_activity"),
    path('create-certificate/', AddCertificate.as_view(), name="create_certificate"),
    path('certificate-list/', CertificateList.as_view(), name="certificate_list"),
    path('update-certificate/<uuid:certificate_id>', UpdateCertificate.as_view(), name="update_certificate"),
]
