version: '3.8'
services:
    backend: 
        build:
            context: .
            dockerfile: Dockerfile
        environment: 
            RAVIN_SECRET_KEY: ${RAVIN_SECRET_KEY}
        ports:
            - 8000:8000
        volumes:
            - .:/app
            