
from django.urls import path
from apps.program_manager_panel.views import(
    SubscriptionOfferList,
    CreateSubscriptionOffer,
    Billing,
    Communication,
    Analytics,
    CreateSubscriptions,
    CreateMenteeRatio,
    SubscriptionsList,
    MenteeRatioList,
    UpdateSubscriptions,
    UpdateSubscriptionOffer,
    UpdateMenteeRatio,
    delete_subscription_offer,
    delete_mentee_ratio,
    delete_subscription,
    Manage,
    Matching,
    Content,
    Security,
    Setup,
    Proxy,
    Activity,
    Calendar,
    RiskPairs,
    Marketplace,
    InviteMentorFromCSV,
    TaskStatusTemplate,
    GenerateAssessmentDataReport,
    ReviewMentorMarketplace,
    GenerateAssessmentDataReport,
    GenerateCertificate,

)
from apps.program_manager_panel.api import CreateTask, UpdateTask, UserSubscriptionList, AssignMentor, UserChatList, UserChatMsg, MentorMenteePairing, \
    AllBadgeList, AllPoints, AlloteUserToJourney, CapacityRatioList, PoolSetup, PoolAllocation, AssessmentList, ArchieveUsers, \
    ContentApproveReject, CreateContentList, CreateListCategory, CreateListIndustry, CreateListTag, EditContentDraft, EditJourneyPageSetup, \
    ForumEvent, GetEditStreams, IssuesRaised, JourneyPageSetup, MatchingQuestions, MatchingQuestionsData, MyJourneyList, PendingContent, \
    ProfileQuestionList, ProgramAnnouncement, ProgramForum, ProgramManagerDataList, ProgramManagerJourneyList, ProgramUserRegistrationList, \
    SpaceDetails, SpaceGroupDetails, StreamList, SurveyList, UpdateCapacityRatio, UserSurveyResponse, UserToken, ViewStreamData, GoalSetting, \
    MentorList, MetneeList, AutoMatching, ManualMatching, ALLSubscriptions, SubscriptionDetail, UserTransactions, AddMentorPool, UpdateMentorPool, \
    MatchingData, MentorMatchingReport, AllUserSubscription, CheckForSubscription, SubscribeFreeSubscription, DefaultCapacityRatio, CompanySubcription, \
    MessageSchedulerView, GroupChatMembersList, RemoveGroupChatMember, AddGroupChatMember, SendNotificationToMentionUser, ManagerCalendar, \
    ReviewMentorForMarketPlace, ApproveRejectMarketplaceMentor, MarketPlaceMentorList, TaskList, UpdateTaskStatus, AssigneeTaskStatusList, CompanyAllUsers, JourneyCompletedUsers, GenerateCertandMail

app_name = 'program_manager'
urlpatterns = [

    path('billing', Billing.as_view(), name="billing"),
    path('communication', Communication.as_view(), name="communication"),
    path('analytics', Analytics.as_view(), name="analytics"),
    path('manage', Manage.as_view(), name="manage"),
    path('create-subscription/', CreateSubscriptions.as_view(), name="create_subscription"),
    path('subscription-list/', SubscriptionsList.as_view(), name="subscription_list"),
    path('update-subscription/<uuid:pk>/', UpdateSubscriptions.as_view(), name="update_subscription"),
    path('delete-subscription/<uuid:subscription_id>/', delete_subscription, name="delete_subscription"),
    path('matching', Matching.as_view(), name="matching"),
    path('content', Content.as_view(), name="content"),
    path('calendar', Calendar.as_view(), name="calendar"),
    path('security', Security.as_view(), name="security"),
    path('setup', Setup.as_view(), name="setup"),
    path('proxy', Proxy.as_view(), name="proxy"),
    path('marketplace', Marketplace.as_view(), name="marketplace"),
    path('generate-certificate', GenerateCertificate.as_view(), name="generate_certificate"),
    path('invite-mentor', InviteMentorFromCSV.as_view(), name="invite_mentor"),
    path('activity', Activity.as_view(), name="activity"),
    path('risk-pairs', RiskPairs.as_view(), name="risk_pairs"),
    path('subscription-offer/', CreateSubscriptionOffer.as_view(), name="subscription_offer"),
    path('mentor-mentee-ratio/', CreateMenteeRatio.as_view(), name="mentor_mentee_ratio"),
    path('subscription-offer-list/', SubscriptionOfferList.as_view(), name="subscription_offer_list"),
    path('mentor-mentee-ratio-list/', MenteeRatioList.as_view(), name="mentor_mentee_ratio_list"),
    path('update-subscription-offer/<uuid:pk>/', UpdateSubscriptionOffer.as_view(), name="update_subscription_offer"),
    path('update-mentor-mentee-ratio/<uuid:pk>/', UpdateMenteeRatio.as_view(), name="update_mentor_mentee_ratio"),
    path('delete-subscription-offer/<uuid:offer_id>/', delete_subscription_offer, name="delete_subscription_offer"),
    path('delete-mentor-mentee-ratio/<uuid:ratio_id>/', delete_mentee_ratio, name="delete_mentor_mentee_ratio"),

    # API urls
    path('issues-raised/<uuid:user_id>/', IssuesRaised.as_view(), name="issues_raised"),
    path('registration-list/<uuid:user_id>/', ProgramUserRegistrationList.as_view(), name="registration_list"),
    path('goal-setting/<uuid:user_id>/', GoalSetting.as_view(), name="goal_setting"),
    path('pending-content/<uuid:user_id>/', PendingContent.as_view(), name="pending_content"),
    path('my-journey-list/<uuid:user_id>/', MyJourneyList.as_view(), name="my_journey_list"),
    path('content-approve-reject/', ContentApproveReject.as_view(), name="content_approve_reject"),
    path('stream-list/<uuid:user_id>/', StreamList.as_view(), name="live_stream_list"),
    path('manager-calendar/<uuid:user_id>/', ManagerCalendar.as_view(), name="manager-calendar"),
    path('get-edit-stream-list/<uuid:user_id>/<uuid:collaborates_id>/', GetEditStreams.as_view(), name="get_edit_stream_list"),
    path('view-stream-data/<uuid:user_id>/<uuid:collaborates_id>/', ViewStreamData.as_view(), name="view_stream_data"),
    path('program-announcement/<uuid:user_id>/', ProgramAnnouncement.as_view(), name="program-announcement"),
    path('user-token/<uuid:user_id>/', UserToken.as_view(), name="user_token"),
    path('forum-event/<uuid:user_id>/', ForumEvent.as_view(), name="forum_event"),
    path('allot-journey-to-user/<uuid:user_id>/', AlloteUserToJourney.as_view(), name="allot_journey_to_user"),
    path('archive-user/<uuid:user_id>/', ArchieveUsers.as_view(), name="archive_user"),
    path('program-data-list/<uuid:user_id>/', ProgramManagerDataList.as_view(), name="program_data_list"),
    path('journey-list/<uuid:user_id>/', ProgramManagerJourneyList.as_view(), name="journey_list"),
    path('matching-questions/<uuid:user_id>/', MatchingQuestions.as_view(), name="matching_questions"),
    path('profile-question-list/<uuid:user_id>/', ProfileQuestionList.as_view(), name="profile_question_list"),
    path('match-question-data/<uuid:user_id>/<uuid:config_id>/', MatchingQuestionsData.as_view(), name="match_question_data"),
    path('tags/<uuid:user_id>/', CreateListTag.as_view(), name="tags"),
    path('industry/<uuid:user_id>/', CreateListIndustry.as_view(), name="industry"),
    path('category/<uuid:user_id>/', CreateListCategory.as_view(), name="category"),
    path('create-content/<uuid:user_id>/', CreateContentList.as_view(), name="create_content"),
    path('edit-content-draft/<uuid:user_id>/<uuid:content_id>/', EditContentDraft.as_view(), name="edit_content_draft"),
    path('surveys/<uuid:user_id>/', SurveyList.as_view(), name="surveys"),
    path('user-survey-response/<uuid:user_id>/', UserSurveyResponse.as_view(), name="user_survey_response"),
    path('program-forum/<uuid:user_id>/', ProgramForum.as_view(), name="program_forum"),
    path('space-details/<uuid:user_id>/', SpaceDetails.as_view(), name="space_details"),
    path('space-group-details/<uuid:user_id>/', SpaceGroupDetails.as_view(), name="space_group_details"),
    path('journey-page-setup/<uuid:user_id>/', JourneyPageSetup.as_view(), name="journey_page_setup"),
    path('edit-journey-page-setup/<uuid:user_id>/', EditJourneyPageSetup.as_view(), name="edit_journey_page_setup"),
    path('assessment/<uuid:user_id>/', AssessmentList.as_view(), name="assessment"),
    path('pool-setup/<uuid:user_id>/', PoolSetup.as_view(), name="pool_setup"),
    path('pool-allocation/<uuid:user_id>/', PoolAllocation.as_view(), name="pool_allocation"),
    path('all-badges/<uuid:user_id>/', AllBadgeList.as_view(), name="all_badges"),
    path('all-points/<uuid:user_id>/', AllPoints.as_view(), name="all_points"),
    path('all-subscription/<uuid:user_id>/', UserSubscriptionList.as_view(), name="all_subscription"),
    path('mentor-mentee-ratio/<uuid:user_id>/', CapacityRatioList.as_view(), name="mentor_mentee_ratio"),
    path('update-ratio/<uuid:user_id>/<uuid:ratio_id>/', UpdateCapacityRatio.as_view(), name="update_ratio"),
    path('mentor-list/<uuid:user_id>/', MentorList.as_view(), name="mentor_list"),
    path('mentee-list/<uuid:user_id>/', MetneeList.as_view(), name="mentee_list"),
    path('auto-matching/<uuid:user_id>/', AutoMatching.as_view(), name="auto_matching"),
    path('manual-matching/<uuid:user_id>/', ManualMatching.as_view(), name="manual_matching"),
    path('mentor-mentee-list/<uuid:user_id>/',MentorMenteePairing.as_view(), name="mentor_mentee_list"),
    path('all-subscription-list/<uuid:user_id>/', ALLSubscriptions.as_view(), name="all_subscription_list"),
    path('subscription-detail/<uuid:user_id>/<uuid:subs_id>/', SubscriptionDetail.as_view(), name="subscription_detail"),
    path('transaction-list/<uuid:user_id>/', UserTransactions.as_view(), name="transaction_list"),
    path('add-mentor-pool/<uuid:user_id>/', AddMentorPool.as_view(), name="add_mentor_pool"),
    path('update-mentor-pool/<uuid:user_id>/', UpdateMentorPool.as_view(), name="upate_mentor_pool"),
    path('matching-data/<uuid:user_id>/', MatchingData.as_view(), name="matching_data"),
    path('assign-mentor/<uuid:user_id>/', AssignMentor.as_view(), name="assign_mentor"),
    path('chat-list/<uuid:mentor_id>/', UserChatList.as_view(), name="chat_list"),
    path('chat-msg/<uuid:mentor_id>/<str:room_name>/', UserChatMsg.as_view(), name="chat_msg"),
    path('mentor-matching-report/<uuid:user_id>/', MentorMatchingReport.as_view(), name="mentor_matching_report"),
    path('user-subscriptions/<uuid:user_id>/', AllUserSubscription.as_view(), name="user_subscriptions"),
    path('check-for-subscription/<uuid:user_id>/', CheckForSubscription.as_view(), name="check_for_subscription"),
    path('subscribe-free-subscripion/<uuid:user_id>/', SubscribeFreeSubscription.as_view(), name="subscribe_free_subscription"),
    path('default-capacity-ratio/<uuid:user_id>/<uuid:subs_id>/', DefaultCapacityRatio.as_view(), name="default_capacity_ratio"),
    path('company-subscription/<uuid:user_id>/<uuid:company_id>/', CompanySubcription.as_view(), name="company_subscription"),
    path('message-scheduler/<uuid:user_id>/', MessageSchedulerView.as_view(), name="message_scheduler"),
    path('groupchat-members-list/<str:room_id>/', GroupChatMembersList.as_view(), name="groupchat_members_list"),
    path('remove-groupchat-member/<uuid:user_id>/', RemoveGroupChatMember.as_view(), name="remove_groupchat_member"),
    path('add-groupchat-member/<uuid:user_id>/', AddGroupChatMember.as_view(), name="add_groupchat_member"),
    path('send-notification-to-mention-user/<uuid:user_id>/', SendNotificationToMentionUser.as_view(), name="send_notification_to_mention_user"),
    path('review-mentor-for-marketplace/<uuid:user_id>/', ReviewMentorForMarketPlace.as_view(), name="review_mentor_for_marketplace"),
    path('approve-reject-marketplace-mentor/<uuid:user_id>/', ApproveRejectMarketplaceMentor.as_view(), name="approve_reject_marketplace_mentor"),
    path('marketplace-mentor-list/<uuid:user_id>/', MarketPlaceMentorList.as_view(), name="marketplace_mentor_list"),
    path('create-task/<uuid:user_id>/', CreateTask.as_view(), name="create_task"),
    path('update-task/<uuid:user_id>/<uuid:task_id>/', UpdateTask.as_view(), name="update_task"),
    path('task-status-template/<uuid:task_id>', TaskStatusTemplate.as_view(), name="task_status_template"),
    path('task-list/<uuid:user_id>/', TaskList.as_view(), name="task_list"),
    path('assessment-response-report/', GenerateAssessmentDataReport.as_view(), name="assessment_response_report"),
    path('update-task-status/<uuid:user_id>/', UpdateTaskStatus.as_view(), name="update_task_status"),
    path('assignee-task-list/<uuid:task_id>', AssigneeTaskStatusList.as_view(), name="assignee_task_list"),
    path('company-all-users/<uuid:user_id>/<uuid:company_id>/', CompanyAllUsers.as_view(), name="company_all_users"),
    path('admin-review-mentor-marketplace', ReviewMentorMarketplace.as_view(), name="admin_review_mentor_marketplace"),
    path('assessment-response-report/', GenerateAssessmentDataReport.as_view(), name="assessment_response_report"),
    path('journey-completed-users/<uuid:user_id>/', JourneyCompletedUsers.as_view(), name="journey_completed_users"),
    path('send-generated-cert-email/<uuid:user_id>/', GenerateCertandMail.as_view(), name="send_generated_cert_email"),
]