from django.urls import path
from .views import (CreateSurvey, SurveyInstruction,
                    SurveyList,
                    AddQuestion,
                    update_question,
                    delete_question,
                    SurveyForm,
                    SubmitSurvey,
                    UserSurveyAttempt,
                    CheckSurvey,
                    CreateLevel,
                    AlloteChannel,
                    CopyQuestion,
                    UpdateQOrder,
                    QuestionId,
                    EditSurvey,
                    DeleteSurvey,
                    Updatelevel,
                    DeleteLevel,
                    all_survey_report,
                    CopySurveys
                    )
app_name = "survey"
urlpatterns = [
    path('create/', CreateSurvey.as_view(), name="create-survey"),
    path('copy-survey/', CopySurveys.as_view(), name="copy_survey"),
    path('list/', SurveyList.as_view(), name="survey-list"),
    path('edit/<uuid:pk>/', EditSurvey.as_view(), name="survey-edit"),
    path('delete/<uuid:pk>/', DeleteSurvey.as_view(), name="survey-delete"),
    path('create-level/', CreateLevel.as_view(), name="create_label"),
    path('edit-level/<uuid:pk>/', Updatelevel.as_view(), name="update-level"),
    path('delete-level/<uuid:pk>/', DeleteLevel.as_view(), name="delete-level"),
    path('add-question/<uuid:survey>/', AddQuestion.as_view(), name="add_survey_questions"),
    path('update-question/', update_question, name="update-question"),
    path('delete-question/<uuid:survey_id>/<int:pk>/', delete_question, name="delete-question"),
    path('survey-question/<uuid:channel>/<uuid:pk>/', SurveyForm.as_view(), name="survey_form"),
    path('survey-instruction/<uuid:channel>/<uuid:pk>/', SurveyInstruction.as_view(), name="survey_instruction"),
    path('submit-survey/', SubmitSurvey.as_view(), name="submit-survey"),
    path('user/', UserSurveyAttempt.as_view(), name="user_survey_attempt"),
    path('check/<uuid:survey_attempt>/', CheckSurvey.as_view(), name="check_survey"),
    path('allote-channel/', AlloteChannel.as_view(), name="addsurvey_to_channel"),
    path('copy-question/', CopyQuestion.as_view(), name="copy_question"),
    path('update-question-order/', UpdateQOrder.as_view(), name='update-q-order'),
    path('question/', QuestionId.as_view(), name="single_question"),
    path('user-survey-report/', all_survey_report, name="all_survey_report"),
]
